```toml
    # Inicio del código para netlify.toml
    # ==================================
    # Este archivo le dice a Netlify cómo servir los archivos de TypeScript.
    
    [[headers]]
      for = "/*.ts"
      [headers.values]
        Content-Type = "text/javascript"
    
    [[headers]]
      for = "/*.tsx"
      [headers.values]
        Content-Type = "text/javascript"
    
    [[headers]]
      for = "/components/*"
      [headers.values]
        Content-Type = "text/javascript"
    
    [[headers]]
      for = "/services/*"
      [headers.values]
        Content-Type = "text/javascript"
    
    # ================================
    # Fin del código para netlify.toml